name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Build
        run: cargo build --release --verbose

      - uses: actions/upload-artifact@v4.0.0
        with:
          name: ${{runner.os}} Binaries
          path: target/release/*